modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/fenn7/Thatchers-Revenge/issues"
license = "CC0-1.0"

[[mods]]
    modId = "thatchermod"
    version = "${version}"
    displayName = "Thatcher's Revenge"
    displayURL = "https://github.com/fenn7/Thatchers-Revenge"
    authors = "fenn7"
    credits = "fenn7, ShaksterNano"
    description = '''
    description": "https://www.youtube.com/watch?v=ILvd5buCEnU
    '''
    logoFile = "icon.png"

[[dependencies.thatchermod]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thatchermod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.thatchermod]]
    modId = "architectury"
    mandatory = true
    versionRange = "[4.10.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.thatchermod]]
    modId = "geckolib3"
    mandatory = true
    versionRange = "[3.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
